chore: configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4,58 +4,36 @@ work_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
 deps_dir=$work_dir/deps
 mkdir -p $deps_dir
 
-# cmake 3.18.0
-if [ ! -f "$deps_dir/cmake-3.18.0-Linux-x86_64.tar.gz" ]; then
-    cd $deps_dir
-    wget -O cmake-3.18.0-Linux-x86_64.tar.gz https://github.com/Kitware/CMake/releases/download/v3.18.0/cmake-3.18.0-Linux-x86_64.tar.gz
-
-    tar -xvf cmake-3.18.0-Linux-x86_64.tar.gz > /dev/null
-    mv cmake-3.18.0-Linux-x86_64 cmake-install
+# cmake
+if ! command -v cmake &> /dev/null; then
+    cmake_install=true
+    echo "cmake not found"
 else
-    echo cmake has already installed
+    cmake_ver="$(cmake --version | head -n1 | cut -d" " -f3)"
+    cmake_reqver=3.14
+    if [ "$(printf '%s\n' "$cmake_reqver" "$cmake_ver" | sort -V | head -n1)" = "$cmake_reqver" ]; then
+        echo "cmake $cmake_ver found, suitable for required version $cmake_reqver"
+    else
+        cmake_install=true
+        echo "cmake $cmake_ver found, but not compatible with required version $cmake_reqver"
+    fi
+fi
+if [ "$cmake_install" = true ]; then
+    cd $deps_dir
+    if [ -f "cmake-install/bin/cmake" ]; then
+        echo "Downloaded cmake found"
+    else
+        wget -nc https://github.com/Kitware/CMake/releases/download/v3.18.0/cmake-3.18.0-Linux-x86_64.tar.gz
+        tar -xvf cmake-3.18.0-Linux-x86_64.tar.gz > /dev/null
+        mv cmake-3.18.0-Linux-x86_64 cmake-install
+    fi
+    PATH=$deps_dir/cmake-install/bin:$PATH
 fi
 
-PATH=$deps_dir/cmake-install/bin:$PATH
+# sdl2 glew
+sudo apt install libsdl2-dev libglew-dev
 
-# apt
-sudo apt install libsdl2-dev libglew-dev libspdlog-dev
-
-# fmt 7.0.1
-if [ ! -f "$deps_dir/fmt-7.0.1.tar.gz" ]; then
-    cd $deps_dir
-    wget -O fmt-7.0.1.tar.gz https://github.com/fmtlib/fmt/archive/7.0.1.tar.gz
-
-    tar -xvf fmt-7.0.1.tar.gz > /dev/null
-    mv fmt-7.0.1 fmt-install
-
-    cd fmt-install
-    mkdir -p out && cd out
-
-    cmake .. -DBUILD_SHARED_LIBS=TRUE -DFMT_TEST=FALSE
-    cmake --build .
-else
-    echo fmt has already installed
-fi
-
-fmt_DIR=$deps_dir/fmt-install/out
-
-# nlohmann-json 3.8.0
-if [ ! -f "$deps_dir/json-3.8.0.tar.gz" ]; then
-    cd $deps_dir
-    wget -O json-3.8.0.tar.gz https://github.com/nlohmann/json/archive/v3.8.0.tar.gz
-
-    tar -xvf json-3.8.0.tar.gz > /dev/null
-    mv json-3.8.0 json-install
-
-    cd json-install
-    mkdir -p out && cd out
-    cmake ..
-else
-    echo nlohmann-json has already installed
-fi
-
-nlohmann_json_DIR=$deps_dir/json-install/out
-
+# generate
 cd $work_dir
 mkdir -p out && cd out
-cmake .. -Dfmt_DIR=$fmt_DIR -Dnlohmann_json_DIR=$nlohmann_json_DIR
+cmake ..
